#!/usr/bin/env python

from optparse import OptionParser
from pyminc.volumes.factory import *
from numpy import *

if __name__ == "__main__":
    
    usage = "usage: %prog [options] input.mnc atlas.mnc output.txt"
    description = "Computes the average value of the input file for each label in the atlas and places the results in a text file."
    parser = OptionParser(usage=usage, description=description)
    
    (options, args) = parser.parse_args()
    
    if len(args) != 3:
        parser.error("Incorrect number of arguments")
    
    inf = volumeFromFile(args[0], dtype="double")
    atlas = volumeFromFile(args[1], dtype='ubyte')
    output = open(args[2], 'w')
    
    labels = unique(atlas.data)
    #print labels

    for l in labels:
        #print(l)
        m = mean(inf.data[atlas.data == l])
        output.write(str(int(l)) + "," + str(m) +  "\n")

    inf.closeVolume()
    atlas.closeVolume()
    output.close()
    
