#!/usr/bin/env python

from pyminc.volumes.factory import *
from numpy import *
from optparse import OptionParser
import re as re


if __name__ == "__main__":

    usage = "usage: %prog [options] input_labels.mnc output_labels.mnc"
    description = """write description here"""

    parser = OptionParser(usage=usage, description=description)

    parser.add_option("--convert", dest="convert",
                      help="Convert input file to labels.",
                      action="store_true", default=False)
    parser.add_option("--merge", dest="merge",
                      help="Second label file to whose labels are to be merged with the input_labels",
                      type="string")
    parser.add_option("--remap", dest="remap",
                      help="Label numbers to replace with new label numbers. For example, to turn label 3 into label 11, it would be --remap 3:11. More than one can be specified at once, separated by commas, i.e. --remap 3:11,21:55. It is also possible to specify a range of values to be remapped as follows: to map 3,4,5,6,7, and 8 onto the value 11, specify --remap 3-8:11. This can also be combined: --remap 3-8:11,66:98.",
                      type="string")
    parser.add_option("--select", dest="select",
                      help="Label numbers to select (comma separated, i.e. 3,7,211) - outfile will be just these labels",
                      type="string")
    parser.add_option("--remove", dest="remove",
                      help="Label numbers to remove (comma separated, i.e. 3,7,211) - outfile will exclude these labels",
                      type="string")
    parser.add_option("--mask", dest="mask",
                      help="Erase all labels where mask >0.5",
                      type="string")
    parser.add_option("--binarize", help="threshold >0.5 and binarize output", action="store_true", default=False)
    parser.add_option("-v", "--verbose", help='verbose output', action='store_true', default=False)

    (options, args) = parser.parse_args()

    if len(args) != 2:
        parser.error("Incorrect number of arguments")
    

    inlabels = volumeFromFile(args[0], dtype='ushort')
    outlabels = volumeLikeFile(args[0], args[1], dtype='ushort', 
                               volumeType="ushort", labels=True)

    if options.verbose:
        print("Labels found in input: %s" % unique(inlabels.data[::]))

    if options.convert == True:
        outlabels.data[::] = rint(inlabels.data[::])

    if options.remap:
        outlabels.data[::] = rint(inlabels.data[::])
        labelpairs = options.remap.split(',')
        # there are two options for a label pair:
        #
        # 1) a 1 to 1 mapping, for example the following will map the
        #    the value 3 to 11:
        #    
        # 3:11
        #
        # 2) a many to 1 mapping, for example the following will map the
        #    values 3,4,5,6, and 7 to the value 11:
        # 
        # 3-7:11
        # 
        for pair in labelpairs:
            labels = pair.split(':')
            dash = re.search('-', labels[0])
            if(dash != None):
                remaprange = (labels[0]).split('-')
                for start in range(int(remaprange[0]),int(remaprange[1])+1):
                    print("Mapping: %d to %d" % (int(start), int(labels[1])))
                    outlabels.data[inlabels.data == int(start)] = int(labels[1])
            else:
                print("Mapping: %d to %d" % (int(labels[0]), int(labels[1])))
                outlabels.data[inlabels.data == int(labels[0])] = int(labels[1])
    
    if options.select:
        labels = options.select.split(',')
        for l in labels:
            outlabels.data[inlabels.data == int(l)] = int(l)

    if options.remove:
        outlabels.data[::] = rint(inlabels.data[::])
        labels = options.remove.split(',')
        for l in labels:
            outlabels.data[inlabels.data == int(l)] = 0

    if options.merge:
        addlabels = volumeFromFile(options.merge, dtype='ushort', labels=True)
        # should add check to make sure dimensions are the same

        # blank one set of labels - i.e. they replace rather than add
        inlabels.data[addlabels.data > 0] = 0
        # now add them together
        outlabels.data[::] = inlabels.data[::] + addlabels.data[::]
        addlabels.closeVolume()
    
    if options.mask:
        maskforlabels = volumeFromFile(options.mask, dtype='ushort')
        # initially copy over input labels
        outlabels.data[::] = rint(inlabels.data[::])
        # then zero out labels where mask > 0.5
        outlabels.data[maskforlabels.data > 0.5] = 0
        maskforlabels.closeVolume()
    
    if options.binarize:
        outlabels.data[outlabels.data > 0.5] = 1

    # write to file
    outlabels.writeFile()
    outlabels.closeVolume()
    inlabels.closeVolume()

