#!/usr/bin/env python

from optparse import OptionParser
from pyminc.volumes.factory import *
from numpy import *

if __name__ == "__main__":
    
    usage = "usage: %prog [options] input.mnc  output.txt"
    description = "Computes the volume of the labels in the input.mnc file places the results in a text file."
    parser = OptionParser(usage=usage, description=description)
    
    (options, args) = parser.parse_args()
    
    if len(args) != 2:
        parser.error("Incorrect number of arguments")
    
    atlas = volumeFromFile(args[0], dtype='ushort', labels=True)
    output = open(args[1], 'w')
    
    volumePerVoxel=atlas.separations[0]*atlas.separations[1]*atlas.separations[2]
    labels = unique(atlas.data)

    for l in labels:
        voxelsPerLabel = len(atlas.data[atlas.data == l])
	volumePerLabel = volumePerVoxel*voxelsPerLabel
        output.write(str(int(l)) + ", " + str(volumePerLabel) +  "\n")

    atlas.closeVolume()
    output.close()
    
